apiVersion: apps/v1
metadata:
  name: create-react-app-docker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: create-react-app-docker
  template:
    metadata:
      labels:
        app: create-react-app-docker
    spec:
      containers:
      - name: create-react-app-docker
        image: create-react-app-docker
        ports:
        - containerPort: 80
